DROP TABLE IF EXISTS "AdminActionLog";
DROP TABLE IF EXISTS "Allocation";
DROP TABLE IF EXISTS "RoommateRequest";
DROP TABLE IF EXISTS "Room";
DROP TABLE IF EXISTS "Preference";
DROP TABLE IF EXISTS "Event";
DROP TABLE IF EXISTS "User";
